name: container-image

# Were we can define the inputs that our action will accept
inputs:
  tag:
    description: "tag for the container image"
    required: false
    default: ${{ github.ref_name }}

outputs:
  ref:
    description: "Container image reference from ko build"
    value: ${{ steps.ko-build.outputs.ref }}

description: "build container image with ko"
runs:
  using: "composite"
  # Defining the action steps(Just one step to be simple)
  steps:
    - uses: actions/setup-go@v4
      with:
        go-version: '1.21.x'
    - uses: ko-build/setup-ko@v0.6
    - shell: bash
      run: echo "ref=$(ko build --tags ${{ inputs.tag }})" >> "$GITHUB_OUTPUT"
      id: ko-build