on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

name: Create Release


jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    # Default GITHUB_TOKEN token permissions do NOT support cosign and must be enabled.
    # This is to set the package and id_token permissions to read|write.
    # Current default permissions can be viewed here: https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token
    permissions:
      packages: write
      id-token: write # To sign the image.
      contents: write # To store the image
    steps:
      - uses: actions/checkout@v3
      - uses: "./.github/actions/container-image"
        id: container-image
      - uses: sigstore/cosign-installer@v3.1.1
      - run: cosign sign --yes $REF
        env:
          REF: ${{ steps.container-image.outputs.ref }}
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body_path: CHANGELOG.md
          draft: false
          prerelease: false